-- ─── MICHT Decants — Cargar los acordes principales de TODOS los perfumes (2026-09-23) ─
--
-- Pega TODO este archivo en Supabase → SQL Editor → Run. Es seguro correrlo más de una vez.
--
-- POR QUÉ: la columna `accords` existe en tu Supabase pero está VACÍA en los 106 perfumes.
-- Los acordes (las barras de colores de la ficha del perfume) solo estaban en el código
-- (catalog.js), que únicamente siembra la base la primera vez; nunca se copiaron a la base.
-- Este archivo los copia. Incluye los que faltaban (Sauvage Elixir ya tenía en el código;
-- se agregaron King of Kings Nebula, Aruba Gold, Stallion Donna Intense, Yara Rosa,
-- Maleka, The Kingdom Dama y los enteros/sets equivalentes).
--
-- SOLO rellena los perfumes que tienen los acordes vacíos: si ya editaste los acordes de
-- alguno desde el panel admin, NO se toca.

UPDATE productos SET accords = '[{"name":"aromático","pct":100},{"name":"fresco especiado","pct":95},{"name":"cítrico","pct":78},{"name":"ámbar","pct":47},{"name":"herbal","pct":37},{"name":"acuático","pct":28},{"name":"almizclado","pct":22},{"name":"fresco","pct":21}]'::jsonb WHERE id = 0 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Louis Vuitton — L'Immensité
UPDATE productos SET accords = '[{"name":"afrutados","pct":100},{"name":"dulce","pct":69},{"name":"amaderado","pct":68},{"name":"cuero","pct":64},{"name":"cítrico","pct":59},{"name":"ahumado","pct":57},{"name":"almizclado","pct":55},{"name":"fresco","pct":52},{"name":"tropical","pct":52},{"name":"musgoso","pct":47}]'::jsonb WHERE id = 1 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Creed — Creed Aventus
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"afrutados","pct":99},{"name":"dulce","pct":83},{"name":"almizclado","pct":74},{"name":"atalcado","pct":67},{"name":"avainillado","pct":62},{"name":"ámbar","pct":55},{"name":"fresco especiado","pct":46}]'::jsonb WHERE id = 2 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Xerjoff — Erba Pura
UPDATE productos SET accords = '[{"name":"dulce","pct":100},{"name":"amaderado","pct":97},{"name":"coco","pct":91},{"name":"ámbar","pct":78},{"name":"avainillado","pct":72},{"name":"tropical","pct":68},{"name":"afrutados","pct":68},{"name":"atalcado","pct":58},{"name":"iris","pct":52},{"name":"lactónico","pct":52}]'::jsonb WHERE id = 3 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Jean Paul Gaultier — Le Beau Le Parfum
UPDATE productos SET accords = '[{"name":"avainillado","pct":100},{"name":"dulce","pct":81},{"name":"amielado","pct":71},{"name":"aromático","pct":60},{"name":"ámbar","pct":59},{"name":"lavanda","pct":54},{"name":"tabaco","pct":50},{"name":"verde","pct":48},{"name":"fresco especiado","pct":46},{"name":"atalcado","pct":46}]'::jsonb WHERE id = 4 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Jean Paul Gaultier — Le Male Elixir
UPDATE productos SET accords = '[{"name":"cálido especiado","pct":100},{"name":"avainillado","pct":80},{"name":"lavanda","pct":66},{"name":"aromático","pct":65},{"name":"atalcado","pct":65},{"name":"iris","pct":64},{"name":"amaderado","pct":59},{"name":"ámbar","pct":55},{"name":"violeta","pct":47}]'::jsonb WHERE id = 5 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Jean Paul Gaultier — Le Male Le Parfum
UPDATE productos SET accords = '[{"name":"avainillado","pct":100},{"name":"iris","pct":89},{"name":"atalcado","pct":79},{"name":"cuero","pct":69},{"name":"violeta","pct":59},{"name":"dulce","pct":54},{"name":"terrosos","pct":54},{"name":"aromático","pct":52},{"name":"animálico","pct":49},{"name":"ámbar","pct":47}]'::jsonb WHERE id = 6 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Valentino — Valentino Intense
UPDATE productos SET accords = '[{"name":"cálido especiado","pct":100},{"name":"dulce","pct":89},{"name":"ámbar","pct":82},{"name":"amaderado","pct":71},{"name":"caramelo","pct":59},{"name":"aromático","pct":57}]'::jsonb WHERE id = 7 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Azzaro — The Most Wanted
UPDATE productos SET accords = '[{"name":"avainillado","pct":100},{"name":"dulce","pct":92},{"name":"ámbar","pct":72},{"name":"canela","pct":70},{"name":"cálido especiado","pct":67},{"name":"atalcado","pct":59},{"name":"aromático","pct":56},{"name":"especiado suave","pct":55},{"name":"caramelo","pct":48}]'::jsonb WHERE id = 8 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Giorgio Armani — Stronger With You Intensely
UPDATE productos SET accords = '[{"name":"amaderado","pct":100},{"name":"cítrico","pct":71},{"name":"aromático","pct":64},{"name":"ámbar","pct":58},{"name":"fresco especiado","pct":56},{"name":"atalcado","pct":49},{"name":"cálido especiado","pct":48},{"name":"verde","pct":47},{"name":"lavanda","pct":47}]'::jsonb WHERE id = 9 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Chanel — Bleu de Chanel Parfum
UPDATE productos SET accords = '[{"name":"aromático","pct":100},{"name":"fresco especiado","pct":98},{"name":"amaderado","pct":81},{"name":"afrutados","pct":71},{"name":"fresco","pct":67},{"name":"ámbar","pct":66},{"name":"cítrico","pct":62},{"name":"herbal","pct":58},{"name":"verde","pct":55},{"name":"cálido especiado","pct":45}]'::jsonb WHERE id = 10 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Yves Saint Laurent — Y EDP
UPDATE productos SET accords = '[{"name":"atalcado","pct":100},{"name":"iris","pct":97},{"name":"avainillado","pct":96},{"name":"amaderado","pct":76},{"name":"ámbar","pct":68},{"name":"terrosos","pct":67},{"name":"violeta","pct":64},{"name":"aromático","pct":44}]'::jsonb WHERE id = 11 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Dior — Homme Intense
UPDATE productos SET accords = '[{"name":"fresco especiado","pct":100},{"name":"ámbar","pct":71},{"name":"cítrico","pct":69},{"name":"aromático","pct":64},{"name":"almizclado","pct":57},{"name":"amaderado","pct":55},{"name":"lavanda","pct":47},{"name":"herbal","pct":46}]'::jsonb WHERE id = 12 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Dior — Dior Sauvage
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"fresco especiado","pct":71},{"name":"avainillado","pct":70},{"name":"aromático","pct":70},{"name":"amaderado","pct":63},{"name":"cálido especiado","pct":53},{"name":"dulce","pct":46},{"name":"atalcado","pct":46}]'::jsonb WHERE id = 13 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Versace — Eros Flame
UPDATE productos SET accords = '[{"name":"almizclado","pct":100},{"name":"aromático","pct":99},{"name":"jabonoso","pct":89},{"name":"marino","pct":89},{"name":"atalcado","pct":83},{"name":"amaderado","pct":79},{"name":"lavanda","pct":75},{"name":"acuático","pct":66},{"name":"ozónico","pct":55},{"name":"salado","pct":53}]'::jsonb WHERE id = 14 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Paco Rabanne — Invictus Parfum
UPDATE productos SET accords = '[{"name":"rosas","pct":100},{"name":"almizclado","pct":58},{"name":"fresco especiado","pct":52},{"name":"cítrico","pct":48},{"name":"aromático","pct":39},{"name":"atalcado","pct":31},{"name":"florales","pct":27},{"name":"herbáceo","pct":17}]'::jsonb WHERE id = 15 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Dior — Rose N Roses
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"atalcado","pct":48},{"name":"acerezado","pct":44},{"name":"almizclado","pct":41},{"name":"amaderado","pct":38},{"name":"dulce","pct":30},{"name":"aromático","pct":21},{"name":"floral blanco","pct":20}]'::jsonb WHERE id = 16 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Dolce & Gabbana — Q
UPDATE productos SET accords = '[{"name":"florales","pct":100},{"name":"rosas","pct":100},{"name":"fresco","pct":66},{"name":"afrutados","pct":44},{"name":"almizclado","pct":38},{"name":"cítrico","pct":35},{"name":"atalcado","pct":34},{"name":"dulce","pct":22}]'::jsonb WHERE id = 17 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Dior — Miss Dior Blooming Bouquet
UPDATE productos SET accords = '[{"name":"amaderado","pct":100},{"name":"aldehídico","pct":79},{"name":"fresco","pct":71},{"name":"floral blanco","pct":68},{"name":"atalcado","pct":56},{"name":"terrosos","pct":53},{"name":"floral amarillo","pct":51},{"name":"iris","pct":43}]'::jsonb WHERE id = 18 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Chanel — N°5
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"afrutados","pct":73},{"name":"dulce","pct":62},{"name":"avainillado","pct":53},{"name":"atalcado","pct":45},{"name":"almizclado","pct":43},{"name":"ámbar","pct":35},{"name":"fresco especiado","pct":23}]'::jsonb WHERE id = 19 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Bharara Beauty — Bharara King
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"aromático","pct":70},{"name":"amaderado","pct":45},{"name":"fresco especiado","pct":33},{"name":"afrutados","pct":33},{"name":"almizclado","pct":31},{"name":"ámbar","pct":29},{"name":"especiado suave","pct":29}]'::jsonb WHERE id = 20 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Alhambra — Sceptre Malachite
UPDATE productos SET accords = '[{"name":"dulce","pct":100},{"name":"afrutados","pct":88},{"name":"ozónico","pct":63},{"name":"avainillado","pct":59},{"name":"atalcado","pct":58},{"name":"almizclado","pct":57},{"name":"fresco","pct":56},{"name":"acuático","pct":54}]'::jsonb WHERE id = 21 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Al Haramain — Amber Oud Gold Edition
UPDATE productos SET accords = '[{"name":"dulce","pct":100},{"name":"cálido especiado","pct":98},{"name":"avainillado","pct":95},{"name":"canela","pct":71},{"name":"floral blanco","pct":45},{"name":"atalcado","pct":44},{"name":"cítrico","pct":40},{"name":"aromático","pct":40}]'::jsonb WHERE id = 22 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Liquid Brun
UPDATE productos SET accords = '[{"name":"avainillado","pct":100},{"name":"ámbar","pct":47},{"name":"cálido especiado","pct":43},{"name":"afrutados","pct":39},{"name":"canela","pct":36},{"name":"dulce","pct":36},{"name":"lavanda","pct":34},{"name":"fresco","pct":30}]'::jsonb WHERE id = 23 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Afnan — 9PM
UPDATE productos SET accords = '[{"name":"amaderado","pct":100},{"name":"afrutados","pct":88},{"name":"cálido especiado","pct":85},{"name":"dulce","pct":83},{"name":"tropical","pct":67},{"name":"aromático","pct":61},{"name":"lavanda","pct":46},{"name":"florales","pct":44}]'::jsonb WHERE id = 24 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Afnan — 9PM Night Out
UPDATE productos SET accords = '[{"name":"afrutados","pct":100},{"name":"verde","pct":96},{"name":"amaderado","pct":94},{"name":"cítrico","pct":81},{"name":"fresco especiado","pct":80},{"name":"aromático","pct":80},{"name":"fresco","pct":73},{"name":"especiado suave","pct":36}]'::jsonb WHERE id = 25 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Afnan — 9AM Dive
UPDATE productos SET accords = '[{"name":"cálido especiado","pct":100},{"name":"avainillado","pct":60},{"name":"aromático","pct":54},{"name":"fresco especiado","pct":50},{"name":"cuero","pct":37},{"name":"lavanda","pct":33},{"name":"balsámico","pct":31},{"name":"pachulí","pct":27}]'::jsonb WHERE id = 26 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Afnan — 9PM Elixir
UPDATE productos SET accords = '[{"name":"afrutados","pct":100},{"name":"dulce","pct":88},{"name":"amaderado","pct":73},{"name":"tropical","pct":43},{"name":"fresco","pct":38},{"name":"musgoso","pct":32},{"name":"ámbar","pct":29},{"name":"caramelo","pct":28}]'::jsonb WHERE id = 27 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Afnan — 9PM Rebel
UPDATE productos SET accords = '[{"name":"ámbar","pct":100},{"name":"avainillado","pct":93},{"name":"cálido especiado","pct":63},{"name":"atalcado","pct":59},{"name":"iris","pct":56},{"name":"amaderado","pct":51},{"name":"aromático","pct":34},{"name":"balsámico","pct":33}]'::jsonb WHERE id = 28 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — His Confession
UPDATE productos SET accords = '[{"name":"cálido especiado","pct":100},{"name":"dulce","pct":82},{"name":"avainillado","pct":73},{"name":"canela","pct":49},{"name":"café","pct":44},{"name":"ámbar","pct":31},{"name":"atalcado","pct":21},{"name":"aromático","pct":19}]'::jsonb WHERE id = 29 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Khamrah Qahwa
UPDATE productos SET accords = '[{"name":"ámbar","pct":100},{"name":"especiado cálido","pct":92},{"name":"dulce","pct":75},{"name":"tabaco","pct":52},{"name":"balsámico","pct":48},{"name":"vainilla","pct":47},{"name":"ahumado","pct":46}]'::jsonb WHERE id = 30 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Khamrah Dukhan
UPDATE productos SET accords = '[{"name":"dulce","pct":100},{"name":"especiado cálido","pct":82},{"name":"vainilla","pct":80},{"name":"ámbar","pct":76},{"name":"canela","pct":69},{"name":"amaderado","pct":49},{"name":"fresco especiado","pct":48},{"name":"afrutado","pct":44}]'::jsonb WHERE id = 31 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Khamrah
UPDATE productos SET accords = '[{"name":"ámbar","pct":100},{"name":"aromático","pct":85},{"name":"mineral","pct":66},{"name":"marino","pct":62},{"name":"especiado suave","pct":59},{"name":"animal","pct":55},{"name":"floral blanco","pct":55},{"name":"salado","pct":45}]'::jsonb WHERE id = 32 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Rasasi — Hawas Fire
UPDATE productos SET accords = '[{"name":"vainilla","pct":100},{"name":"aromático","pct":82},{"name":"verde","pct":70},{"name":"dulce","pct":65},{"name":"fresco especiado","pct":65},{"name":"especiado cálido","pct":59},{"name":"ámbar","pct":59},{"name":"chocolate","pct":56},{"name":"lavanda","pct":54},{"name":"empolvado","pct":51}]'::jsonb WHERE id = 33 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Rasasi — Hawas Elixir
UPDATE productos SET accords = '[{"name":"afrutado","pct":100},{"name":"cítrico","pct":92},{"name":"dulce","pct":57},{"name":"fresco","pct":54},{"name":"aromático","pct":52},{"name":"almizclado","pct":51},{"name":"empolvado","pct":49},{"name":"fresco especiado","pct":49},{"name":"verde","pct":47},{"name":"ámbar","pct":46}]'::jsonb WHERE id = 34 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Rasasi — Hawas Ice
UPDATE productos SET accords = '[{"name":"afrutado","pct":100},{"name":"cítrico","pct":97},{"name":"acuático","pct":86},{"name":"fresco","pct":80},{"name":"especiado cálido","pct":64},{"name":"dulce","pct":58},{"name":"ámbar","pct":57},{"name":"almizclado","pct":55},{"name":"aromático","pct":55},{"name":"animal","pct":53}]'::jsonb WHERE id = 35 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Rasasi — Hawas For Him
UPDATE productos SET accords = '[{"name":"amaderado","pct":100},{"name":"ozónico","pct":96},{"name":"acuático","pct":94},{"name":"afrutado","pct":84},{"name":"lavanda","pct":69},{"name":"ámbar","pct":68},{"name":"fresco especiado","pct":65},{"name":"cítrico","pct":61},{"name":"aromático","pct":60},{"name":"especiado cálido","pct":59}]'::jsonb WHERE id = 36 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Nitro Red
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"ámbar","pct":94},{"name":"aromático","pct":84},{"name":"dulce","pct":83},{"name":"fresco especiado","pct":77},{"name":"floral blanco","pct":72},{"name":"especiado cálido","pct":65},{"name":"verde","pct":60},{"name":"animal","pct":59},{"name":"afrutado","pct":51}]'::jsonb WHERE id = 37 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Nitro Elixir
UPDATE productos SET accords = '[{"name":"amaderado","pct":100},{"name":"marino","pct":73},{"name":"afrutado","pct":70},{"name":"salado","pct":69},{"name":"dulce","pct":63},{"name":"aromático","pct":62},{"name":"cítrico","pct":59},{"name":"especiado cálido","pct":54},{"name":"fresco especiado","pct":53},{"name":"ámbar","pct":53}]'::jsonb WHERE id = 38 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Nitro Gold
UPDATE productos SET accords = '[{"name":"ámbar","pct":100},{"name":"amaderado","pct":90},{"name":"tabaco","pct":83},{"name":"avainillado","pct":69},{"name":"dulce","pct":67},{"name":"cálido especiado","pct":66},{"name":"atalcado","pct":61},{"name":"especiado suave","pct":54},{"name":"pachulí","pct":52},{"name":"fresco especiado","pct":49}]'::jsonb WHERE id = 39 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Asad Elixir
UPDATE productos SET accords = '[{"name":"avainillado","pct":100},{"name":"cacao","pct":91},{"name":"dulce","pct":76},{"name":"lavanda","pct":76},{"name":"fresco especiado","pct":70},{"name":"cálido especiado","pct":66},{"name":"ámbar","pct":65},{"name":"aromático","pct":63},{"name":"atalcado","pct":59},{"name":"especiado suave","pct":57}]'::jsonb WHERE id = 40 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Asad Bourbon
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"caramelo","pct":75},{"name":"dulce","pct":73},{"name":"ámbar","pct":57},{"name":"aromático","pct":54},{"name":"avainillado","pct":48},{"name":"amaderado","pct":46}]'::jsonb WHERE id = 41 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf Odyssey — Mandarin Sky
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"aromático","pct":85},{"name":"fresco especiado","pct":80},{"name":"dulce","pct":54},{"name":"amaderado","pct":54},{"name":"fresco","pct":49},{"name":"verde","pct":47},{"name":"almizclado","pct":46},{"name":"afrutados","pct":46}]'::jsonb WHERE id = 42 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Odyssey Mega
UPDATE productos SET accords = '[{"name":"aromático","pct":100},{"name":"cítrico","pct":89},{"name":"fresco especiado","pct":88},{"name":"verde","pct":74},{"name":"amaderado","pct":61},{"name":"ámbar","pct":58},{"name":"herbal","pct":53},{"name":"lavanda","pct":51},{"name":"pachulí","pct":48},{"name":"almizclado","pct":47}]'::jsonb WHERE id = 43 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Odyssey Aqua
UPDATE productos SET accords = '[{"name":"amaderado","pct":100},{"name":"aromático","pct":82},{"name":"avainillado","pct":80},{"name":"ámbar","pct":79},{"name":"cálido especiado","pct":78},{"name":"especiado suave","pct":64},{"name":"dulce","pct":52},{"name":"atalcado","pct":51},{"name":"marino","pct":46}]'::jsonb WHERE id = 44 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Odyssey White
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"fresco especiado","pct":46},{"name":"aromático","pct":46},{"name":"fresco","pct":43},{"name":"verde","pct":42}]'::jsonb WHERE id = 45 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Odyssey Limoni
UPDATE productos SET accords = '[{"name":"tropical","pct":100},{"name":"afrutados","pct":89},{"name":"dulce","pct":86},{"name":"amaderado","pct":65},{"name":"cítrico","pct":57},{"name":"avainillado","pct":57},{"name":"ámbar","pct":54},{"name":"terpénico","pct":52},{"name":"floral blanco","pct":48},{"name":"almizclado","pct":48}]'::jsonb WHERE id = 46 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Odyssey Mango
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"fresco especiado","pct":79},{"name":"aromático","pct":72},{"name":"dulce","pct":69},{"name":"amaderado","pct":66},{"name":"afrutados","pct":49},{"name":"caramelo","pct":46},{"name":"lavanda","pct":46},{"name":"ámbar","pct":45},{"name":"almizclado","pct":45}]'::jsonb WHERE id = 47 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Eter — Eter Arabian Sky
UPDATE productos SET accords = '[{"name":"afrutados","pct":100},{"name":"floral blanco","pct":88},{"name":"tropical","pct":76},{"name":"dulce","pct":66},{"name":"avainillado","pct":58},{"name":"almizclado","pct":50},{"name":"cítrico","pct":42},{"name":"amaderado","pct":34}]'::jsonb WHERE id = 48 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Aruba Gold
UPDATE productos SET accords = '[{"name":"dulce","pct":100},{"name":"avainillado","pct":42},{"name":"lactónico","pct":32},{"name":"afrutados","pct":31},{"name":"tropical","pct":20},{"name":"atalcado","pct":13},{"name":"almizclado","pct":9},{"name":"verde","pct":9}]'::jsonb WHERE id = 49 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Eclaire Banoffi
UPDATE productos SET accords = '[{"name":"afrutados","pct":100},{"name":"dulce","pct":83},{"name":"pachulí","pct":41},{"name":"caramelo","pct":31},{"name":"amaderado","pct":26},{"name":"almizclado","pct":26},{"name":"cálido especiado","pct":25},{"name":"fresco especiado","pct":24}]'::jsonb WHERE id = 50 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Odyssey Candee
UPDATE productos SET accords = '[{"name":"dulce","pct":100},{"name":"avainillado","pct":58},{"name":"caramelo","pct":48},{"name":"lactónico","pct":43},{"name":"amielado","pct":21},{"name":"atalcado","pct":20},{"name":"almizclado","pct":12},{"name":"balsámico","pct":11}]'::jsonb WHERE id = 51 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Eclaire
UPDATE productos SET accords = '[{"name":"avainillado","pct":100},{"name":"dulce","pct":77},{"name":"lactónico","pct":68},{"name":"cacao","pct":52},{"name":"amaderado","pct":32},{"name":"nueces","pct":31},{"name":"cálido especiado","pct":31},{"name":"atalcado","pct":28}]'::jsonb WHERE id = 52 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Eclaire Pistache
UPDATE productos SET accords = '[{"name":"rosas","pct":100},{"name":"avainillado","pct":90},{"name":"floral blanco","pct":78},{"name":"dulce","pct":70},{"name":"ámbar","pct":62},{"name":"almizclado","pct":55},{"name":"afrutados","pct":47},{"name":"atalcado","pct":40}]'::jsonb WHERE id = 53 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Stallion — Stallion Donna Intense
UPDATE productos SET accords = '[{"name":"avainillado","pct":100},{"name":"caramelo","pct":92},{"name":"dulce","pct":71},{"name":"floral blanco","pct":69},{"name":"atalcado","pct":59},{"name":"afrutados","pct":56},{"name":"ámbar","pct":46},{"name":"almizclado","pct":43}]'::jsonb WHERE id = 54 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Yara Elixir
UPDATE productos SET accords = '[{"name":"amaderado","pct":100},{"name":"floral blanco","pct":96},{"name":"pachulí","pct":73},{"name":"cálido especiado","pct":59},{"name":"caramelo","pct":56},{"name":"atalcado","pct":46},{"name":"ámbar","pct":42},{"name":"afrutados","pct":42}]'::jsonb WHERE id = 55 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Yara Moi
UPDATE productos SET accords = '[{"name":"rosas","pct":100},{"name":"florales","pct":88},{"name":"afrutados","pct":72},{"name":"almizclado","pct":62},{"name":"cítrico","pct":48},{"name":"atalcado","pct":44},{"name":"amaderado","pct":38},{"name":"ámbar","pct":30}]'::jsonb WHERE id = 56 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Yara Rosa
UPDATE productos SET accords = '[{"name":"amaderado","pct":100},{"name":"afrutados","pct":64},{"name":"rosas","pct":64},{"name":"florales","pct":57},{"name":"atalcado","pct":50},{"name":"aromático","pct":49},{"name":"violeta","pct":49},{"name":"fresco","pct":44}]'::jsonb WHERE id = 57 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Afnan — 9PM Pour Femme
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"afrutados","pct":87},{"name":"dulce","pct":51},{"name":"almizclado","pct":47},{"name":"ámbar","pct":42},{"name":"atalcado","pct":32},{"name":"fresco especiado","pct":28},{"name":"animálico","pct":20}]'::jsonb WHERE id = 58 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Afnan — 9AM Pour Femme
UPDATE productos SET accords = '[{"name":"rosas","pct":100},{"name":"florales","pct":64},{"name":"afrutados","pct":59},{"name":"almizclado","pct":52},{"name":"fresco","pct":47},{"name":"atalcado","pct":40},{"name":"verde","pct":36},{"name":"aromático","pct":30}]'::jsonb WHERE id = 59 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Delilah
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"almizclado","pct":63},{"name":"aromático","pct":59},{"name":"amaderado","pct":59},{"name":"cálido especiado","pct":53},{"name":"lavanda","pct":51},{"name":"atalcado","pct":47},{"name":"musgoso","pct":47},{"name":"afrutados","pct":47},{"name":"terrosos","pct":47}]'::jsonb WHERE id = 60 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Afnan — 9AM
UPDATE productos SET accords = '[{"name":"amaderado","pct":100},{"name":"afrutados","pct":88},{"name":"cálido especiado","pct":85},{"name":"dulce","pct":83},{"name":"tropical","pct":67},{"name":"aromático","pct":61},{"name":"lavanda","pct":46},{"name":"florales","pct":44}]'::jsonb WHERE id = 61 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Afnan — 9PM Night Out
UPDATE productos SET accords = '[{"name":"avainillado","pct":100},{"name":"ámbar","pct":47},{"name":"cálido especiado","pct":43},{"name":"afrutados","pct":39},{"name":"canela","pct":36},{"name":"dulce","pct":36},{"name":"lavanda","pct":34},{"name":"fresco","pct":30}]'::jsonb WHERE id = 62 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Afnan — 9PM
UPDATE productos SET accords = '[{"name":"dulce","pct":100},{"name":"especiado cálido","pct":82},{"name":"vainilla","pct":80},{"name":"ámbar","pct":76},{"name":"canela","pct":69},{"name":"amaderado","pct":49},{"name":"fresco especiado","pct":48},{"name":"afrutado","pct":44}]'::jsonb WHERE id = 63 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Khamrah Clásico
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"aromático","pct":85},{"name":"fresco especiado","pct":80},{"name":"dulce","pct":54},{"name":"amaderado","pct":54},{"name":"fresco","pct":49},{"name":"verde","pct":47},{"name":"almizclado","pct":46},{"name":"afrutados","pct":46}]'::jsonb WHERE id = 64 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Odyssey Mega Gift Set
UPDATE productos SET accords = '[{"name":"afrutados","pct":100},{"name":"floral blanco","pct":88},{"name":"tropical","pct":76},{"name":"dulce","pct":66},{"name":"avainillado","pct":58},{"name":"almizclado","pct":50},{"name":"cítrico","pct":42},{"name":"amaderado","pct":34}]'::jsonb WHERE id = 65 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Aruba Gold Entero
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"afrutados","pct":99},{"name":"dulce","pct":83},{"name":"almizclado","pct":74},{"name":"atalcado","pct":67},{"name":"avainillado","pct":62},{"name":"ámbar","pct":55},{"name":"fresco especiado","pct":46}]'::jsonb WHERE id = 66 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Xerjoff — Erba Pura Entero
UPDATE productos SET accords = '[{"name":"ámbar","pct":100},{"name":"especiado cálido","pct":92},{"name":"dulce","pct":75},{"name":"tabaco","pct":52},{"name":"balsámico","pct":48},{"name":"vainilla","pct":47},{"name":"ahumado","pct":46}]'::jsonb WHERE id = 67 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Khamrah Dukhan Entero
UPDATE productos SET accords = '[{"name":"cálido especiado","pct":100},{"name":"dulce","pct":82},{"name":"avainillado","pct":73},{"name":"canela","pct":49},{"name":"café","pct":44},{"name":"ámbar","pct":31},{"name":"atalcado","pct":21},{"name":"aromático","pct":19}]'::jsonb WHERE id = 68 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Khamrah Qahwa Entero
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"caramelo","pct":75},{"name":"dulce","pct":73},{"name":"ámbar","pct":57},{"name":"aromático","pct":54},{"name":"avainillado","pct":48},{"name":"amaderado","pct":46}]'::jsonb WHERE id = 69 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Odyssey Mandarin Sky Entero
UPDATE productos SET accords = '[{"name":"avainillado","pct":100},{"name":"ámbar","pct":47},{"name":"cálido especiado","pct":43},{"name":"afrutados","pct":39},{"name":"canela","pct":36},{"name":"dulce","pct":36},{"name":"lavanda","pct":34},{"name":"fresco","pct":30}]'::jsonb WHERE id = 70 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Afnan — Set de 9PM
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"aromático","pct":70},{"name":"amaderado","pct":45},{"name":"fresco especiado","pct":33},{"name":"afrutados","pct":33},{"name":"almizclado","pct":31},{"name":"ámbar","pct":29},{"name":"especiado suave","pct":29}]'::jsonb WHERE id = 71 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Spectre Malacrite
UPDATE productos SET accords = '[{"name":"rosas","pct":100},{"name":"avainillado","pct":90},{"name":"floral blanco","pct":78},{"name":"dulce","pct":70},{"name":"ámbar","pct":62},{"name":"almizclado","pct":55},{"name":"afrutados","pct":47},{"name":"atalcado","pct":40}]'::jsonb WHERE id = 72 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Stallion — Stallion Donna Intense Entero
UPDATE productos SET accords = '[{"name":"afrutados","pct":100},{"name":"amaderado","pct":94},{"name":"fresco","pct":74},{"name":"ámbar","pct":66},{"name":"atalcado","pct":62},{"name":"ozónico","pct":61},{"name":"acuático","pct":60},{"name":"salado","pct":53},{"name":"verde","pct":52},{"name":"cítrico","pct":51}]'::jsonb WHERE id = 73 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Nitro Red Intensely
UPDATE productos SET accords = '[{"name":"mineral","pct":100},{"name":"amaderado","pct":95},{"name":"ozónico","pct":89},{"name":"aromático","pct":80},{"name":"acuático","pct":73},{"name":"salado","pct":64},{"name":"herbal","pct":60},{"name":"fresco especiado","pct":58},{"name":"verde","pct":54},{"name":"especiado suave","pct":49}]'::jsonb WHERE id = 74 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Valentino — Valentino Uomo Born in Roma
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"vainilla","pct":94},{"name":"fresco especiado","pct":92},{"name":"aromático","pct":83},{"name":"empolvado","pct":65},{"name":"amaderado","pct":65},{"name":"dulce","pct":62},{"name":"ozónico","pct":57},{"name":"verde","pct":57},{"name":"almizclado","pct":55}]'::jsonb WHERE id = 75 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Khamrah Waha
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"fresco especiado","pct":97},{"name":"fresco","pct":75},{"name":"almizclado","pct":70},{"name":"amaderado","pct":61},{"name":"verde","pct":59},{"name":"empolvado","pct":57},{"name":"ámbar","pct":56},{"name":"canela","pct":55},{"name":"especiado cálido","pct":50}]'::jsonb WHERE id = 76 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Rasasi — Hawas Kobra
UPDATE productos SET accords = '[{"name":"afrutado","pct":100},{"name":"dulce","pct":81},{"name":"tropical","pct":67},{"name":"almizclado","pct":56},{"name":"empolvado","pct":53},{"name":"ámbar","pct":53},{"name":"acuático","pct":50},{"name":"fresco","pct":49}]'::jsonb WHERE id = 77 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Rasasi — Hawas Chrome
UPDATE productos SET accords = '[{"name":"dulce","pct":100},{"name":"ámbar","pct":84},{"name":"cítrico","pct":80},{"name":"afrutado","pct":77},{"name":"empolvado","pct":69},{"name":"vainilla","pct":61},{"name":"almizclado","pct":59},{"name":"iris","pct":58},{"name":"aromático","pct":58},{"name":"amaderado","pct":56}]'::jsonb WHERE id = 78 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Rasasi — Hawas Malibu
UPDATE productos SET accords = '[{"name":"dulce","pct":100},{"name":"verde","pct":99},{"name":"amaderado","pct":93},{"name":"coco","pct":92},{"name":"vainilla","pct":77},{"name":"fresco","pct":66},{"name":"aromático","pct":66},{"name":"empolvado","pct":65},{"name":"lactónico","pct":64},{"name":"afrutado","pct":61}]'::jsonb WHERE id = 79 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Rasasi — Hawas Tropical
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"aromático","pct":86},{"name":"fresco especiado","pct":85},{"name":"amaderado","pct":83},{"name":"pachulí","pct":65},{"name":"afrutado","pct":61},{"name":"verde","pct":59},{"name":"ámbar","pct":55},{"name":"conífero","pct":51},{"name":"fresco","pct":49}]'::jsonb WHERE id = 80 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Rasasi — Hawas Verde
UPDATE productos SET accords = '[{"name":"avainillado","pct":100},{"name":"cálido especiado","pct":70},{"name":"ámbar","pct":63},{"name":"aromático","pct":57},{"name":"dulce","pct":54},{"name":"balsámico","pct":53},{"name":"lavanda","pct":48},{"name":"fresco especiado","pct":47},{"name":"ahumado","pct":45},{"name":"atalcado","pct":44}]'::jsonb WHERE id = 81 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Paco Rabanne — Invictus Victory Elixir
UPDATE productos SET accords = '[{"name":"afrutados","pct":100},{"name":"fresco","pct":45},{"name":"tropical","pct":24},{"name":"rosas","pct":23},{"name":"verde","pct":21},{"name":"terrosos","pct":21},{"name":"musgoso","pct":21},{"name":"avainillado","pct":20}]'::jsonb WHERE id = 82 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Badee Al Oud Sublime
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"afrutados","pct":58},{"name":"cuero","pct":46},{"name":"ahumado","pct":36},{"name":"amaderado","pct":36},{"name":"aromático","pct":34},{"name":"dulce","pct":31},{"name":"fresco","pct":30}]'::jsonb WHERE id = 83 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Club de Nuit Intense
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"fresco especiado","pct":57},{"name":"ámbar","pct":45},{"name":"fresco","pct":39},{"name":"verde","pct":29},{"name":"amaderado","pct":22},{"name":"almizclado","pct":19},{"name":"cálido especiado","pct":15}]'::jsonb WHERE id = 84 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Al Wataniah — Game Of Spades Full House
UPDATE productos SET accords = '[{"name":"ámbar","pct":100},{"name":"avainillado","pct":79},{"name":"florales","pct":70},{"name":"afrutados","pct":46},{"name":"amaderado","pct":44},{"name":"cítrico","pct":42},{"name":"aromático","pct":40},{"name":"almizclado","pct":34}]'::jsonb WHERE id = 85 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Al Wataniah — Game Of Spades Wildcard 3.4
UPDATE productos SET accords = '[{"name":"marino","pct":100},{"name":"aromático","pct":98},{"name":"cítrico","pct":81},{"name":"fresco especiado","pct":67},{"name":"fresco","pct":65},{"name":"amaderado","pct":61},{"name":"mineral","pct":59},{"name":"salado","pct":47},{"name":"lavanda","pct":45}]'::jsonb WHERE id = 86 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Giorgio Armani — Acqua di Giò Profondo
UPDATE productos SET accords = '[{"name":"marino","pct":100},{"name":"acuático","pct":96},{"name":"afrutados","pct":81},{"name":"dulce","pct":67},{"name":"salado","pct":67},{"name":"fresco","pct":65},{"name":"ozónico","pct":58},{"name":"aromático","pct":56},{"name":"ámbar","pct":49},{"name":"almizclado","pct":48}]'::jsonb WHERE id = 87 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Odyssey Bahamas
UPDATE productos SET accords = '[{"name":"avainillado","pct":100},{"name":"coco","pct":79},{"name":"dulce","pct":74},{"name":"ámbar","pct":72},{"name":"tropical","pct":71},{"name":"cítrico","pct":63},{"name":"aromático","pct":61},{"name":"nueces","pct":60},{"name":"cálido especiado","pct":54},{"name":"canela","pct":53}]'::jsonb WHERE id = 88 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Odyssey Artisto
UPDATE productos SET accords = '[{"name":"cítrico","pct":100},{"name":"avainillado","pct":85},{"name":"dulce","pct":75},{"name":"caramelo","pct":66},{"name":"cálido especiado","pct":59},{"name":"aromático","pct":59},{"name":"ámbar","pct":52},{"name":"balsámico","pct":50},{"name":"fresco especiado","pct":50},{"name":"lavanda","pct":50}]'::jsonb WHERE id = 89 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Odyssey Mandarin Sky Elixir
UPDATE productos SET accords = '[{"name":"dulce","pct":100},{"name":"tropical","pct":90},{"name":"afrutados","pct":88},{"name":"coco","pct":68},{"name":"ámbar","pct":68},{"name":"amaderado","pct":67},{"name":"aromático","pct":65},{"name":"ron","pct":64},{"name":"marino","pct":64},{"name":"atalcado","pct":57}]'::jsonb WHERE id = 90 AND (accords IS NULL OR accords = '[]'::jsonb);  -- King of Kings — King of Kings Chapter 1
UPDATE productos SET accords = '[{"name":"ahumado","pct":100},{"name":"ámbar","pct":88},{"name":"amaderado","pct":80},{"name":"cálido especiado","pct":72},{"name":"oud","pct":62},{"name":"balsámico","pct":54},{"name":"almizclado","pct":47},{"name":"cítrico","pct":38}]'::jsonb WHERE id = 91 AND (accords IS NULL OR accords = '[]'::jsonb);  -- King of Kings — King of Kings Nebula
UPDATE productos SET accords = '[{"name":"florales","pct":100},{"name":"rosas","pct":90},{"name":"afrutados","pct":80},{"name":"avainillado","pct":68},{"name":"dulce","pct":60},{"name":"almizclado","pct":52},{"name":"ámbar","pct":44},{"name":"amaderado","pct":36}]'::jsonb WHERE id = 92 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Maleka
UPDATE productos SET accords = '[{"name":"amaderado","pct":100},{"name":"oud","pct":90},{"name":"cálido especiado","pct":82},{"name":"ámbar","pct":72},{"name":"rosas","pct":60},{"name":"afrutados","pct":50},{"name":"almizclado","pct":46},{"name":"cítrico","pct":38}]'::jsonb WHERE id = 93 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Ard Al Zaafaran — The Kingdom Dama
UPDATE productos SET accords = '[{"name":"avainillado","pct":100},{"name":"dulce","pct":96},{"name":"cacao","pct":64},{"name":"cálido especiado","pct":55},{"name":"ámbar","pct":54},{"name":"afrutados","pct":54},{"name":"atalcado","pct":51}]'::jsonb WHERE id = 94 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Lattafa — Nebras
UPDATE productos SET accords = '[{"name":"lavanda","pct":100},{"name":"amaderado","pct":69},{"name":"cálido especiado","pct":67},{"name":"aromático","pct":58},{"name":"fresco especiado","pct":51}]'::jsonb WHERE id = 95 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Valentino — Valentino Extradose
UPDATE productos SET accords = '[{"name":"afrutados","pct":100},{"name":"atalcado","pct":96},{"name":"acerezado","pct":71},{"name":"amaderado","pct":70},{"name":"rosas","pct":66},{"name":"dulce","pct":65},{"name":"avainillado","pct":62},{"name":"cítrico","pct":61},{"name":"floral blanco","pct":59},{"name":"almizclado","pct":57}]'::jsonb WHERE id = 96 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Yum Yum
UPDATE productos SET accords = '[{"name":"caramelo","pct":100},{"name":"avainillado","pct":96},{"name":"floral blanco","pct":79},{"name":"dulce","pct":71},{"name":"salado","pct":54},{"name":"atalcado","pct":50},{"name":"balsámico","pct":47}]'::jsonb WHERE id = 97 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Jean Paul Gaultier — Scandal Le Parfum
UPDATE productos SET accords = '[{"name":"avainillado","pct":100},{"name":"cálido especiado","pct":90},{"name":"aromático","pct":61},{"name":"ámbar","pct":61},{"name":"dulce","pct":54},{"name":"fresco especiado","pct":52},{"name":"lavanda","pct":52},{"name":"balsámico","pct":51}]'::jsonb WHERE id = 98 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Tag
UPDATE productos SET accords = '[{"name":"ámbar","pct":100},{"name":"dulce","pct":96},{"name":"avainillado","pct":94},{"name":"cálido especiado","pct":84},{"name":"canela","pct":72},{"name":"cítrico","pct":65},{"name":"afrutados","pct":57},{"name":"balsámico","pct":51},{"name":"atalcado","pct":46}]'::jsonb WHERE id = 99 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Paco Rabanne — 1 Million Night Elixir
UPDATE productos SET accords = '[{"name":"aromático","pct":100},{"name":"fresco especiado","pct":84},{"name":"amaderado","pct":77},{"name":"cítrico","pct":76},{"name":"marino","pct":73},{"name":"pachulí","pct":56},{"name":"ámbar","pct":52},{"name":"cálido especiado","pct":51},{"name":"salado","pct":47},{"name":"herbal","pct":45}]'::jsonb WHERE id = 100 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Odyssey Nexus
UPDATE productos SET accords = '[{"name":"amaderado","pct":100},{"name":"aromático","pct":89},{"name":"lavanda","pct":87},{"name":"avainillado","pct":55},{"name":"ámbar","pct":54},{"name":"fresco especiado","pct":51},{"name":"marino","pct":49},{"name":"terrosos","pct":49},{"name":"atalcado","pct":47},{"name":"acuático","pct":45}]'::jsonb WHERE id = 101 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Stallion — Uomo Intense
UPDATE productos SET accords = '[{"name":"ámbar","pct":100},{"name":"aromático","pct":82},{"name":"cítrico","pct":74},{"name":"fresco especiado","pct":73},{"name":"almizclado","pct":67},{"name":"amaderado","pct":66},{"name":"lavanda","pct":58},{"name":"especiado suave","pct":54},{"name":"cálido especiado","pct":46},{"name":"herbal","pct":46}]'::jsonb WHERE id = 102 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Armaf — Club de Nuit Urban Man Elixir
UPDATE productos SET accords = '[{"name":"avainillado","pct":100},{"name":"especiado suave","pct":80},{"name":"dulce","pct":54},{"name":"lavanda","pct":53},{"name":"balsámico","pct":31},{"name":"atalcado","pct":30},{"name":"anís","pct":23},{"name":"aromático","pct":21}]'::jsonb WHERE id = 103 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Carolina Herrera — 212 VIP Black Elixir
UPDATE productos SET accords = '[{"name":"cuero","pct":100},{"name":"afrutados","pct":95},{"name":"dulce","pct":67},{"name":"aromático","pct":62},{"name":"animálico","pct":49},{"name":"cítrico","pct":42},{"name":"cálido especiado","pct":36},{"name":"ahumado","pct":30}]'::jsonb WHERE id = 104 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Azzaro — Forever Wanted Elixir
UPDATE productos SET accords = '[{"name":"ámbar","pct":100},{"name":"cálido especiado","pct":88},{"name":"amaderado","pct":74},{"name":"aromático","pct":62},{"name":"especiado suave","pct":58},{"name":"dulce","pct":45},{"name":"lavanda","pct":40},{"name":"almizclado","pct":33}]'::jsonb WHERE id = 105 AND (accords IS NULL OR accords = '[]'::jsonb);  -- Dior — Sauvage Elixir

-- Comprobación: debe decir 0 en "sin_acordes"
SELECT count(*) FILTER (WHERE accords IS NULL OR accords = '[]'::jsonb) AS sin_acordes, count(*) AS total FROM productos;
